#+title: 信号

* 信号的概念
信号是软件中断，信号提供了一种处理异步事件的方法。
不存在编号为 0 的信号
** 当信号出现时，应用程序可以采取的三种处理方式
1. 忽略此信号。但是又两种信号不能忽略，他们是 SIGKILL 和 SIGSTOP。这两个信号不能忽略的原因是：他们向内核和 root 用户提供了是进程终止或停止的可靠方法。
2. 捕捉信号。需要通知内核在某种信号发生时，调用一个用户函数。
3. 执行系统默认动作。绝大多数信号的系统默认动作是终止该进程
** core 文件
当应用进程异常终止时，如果开启了生成 core 文件，就会在指定目录下生成 core 文件。
*** 开启生成 core 文件
#+begin_src shell
ulimit -a #查看core文件开启状态 如果是0表示未开启
ulimit -c 0 #不生成core文件
ulimit -c 100 #最大生成100kb的core文件
ulimit -c unlimited #生成core文件，没有大小限制
#+end_src
*** 设置 core 文件的名称
1. core 文件名中加入进程 ID 。src_shell{echo 1 > /proc/sys/kernel/core_uses_pid}
2. 在 /proc/sys/kernel/core_pattern 文件中设置 core 文件名的生成规则。格式如下
#+begin_src shell
/corefile/core.%e.%p
## 参数解释如下：
## %p 添加进程ID
## %u 添加当前用户ID
## %g 添加当前组ID
## %s 添加导致产生core文件的信号ID
## %t 添加产生core文件的unix时间戳
## %h 添加主机名
## %e 添加导致产生core文件的命令名
#+end_src
*** 下列条件下不会产生 core 文件
1. 进程是设置用户 ID 的，而且当前用户并非程序文件的所有者
2. 进程是设置组 ID 的，而且当前用户并非程序文件的组所有者
3. 用户没有写当前工作目录的权限
4. 文件已存在，而且用户对该文件设有写权限
5. 文件太大，超过 RLIMIT_CORE 限制
** 信号说明
*** SIGABRT
产生方式：调用 abort 函数时会产生此信号
默认动作：终止+core
*** SIGALRM
产生方式：调用 alarm 函数设置定时器超时时产生此信号。setitimer 函数设置的间隔时间超时时也会产生此信号
默认动作：终止
*** SIGBUG
产生方式：由实现定义的硬件故障。常常用于当出现某些类型的内存故障时会产生此信号。
默认动作：终止+core
*** SIGCHLD
产生方式：当一个进程终止或停止时，其父进程会收到此信号。
默认动作：忽略
常用技巧：通常自己写的程序从会捕捉该信号，在信号处理函数中调用 wait 函数来获取子进程的终止状态等信息
*** SIGCONT
产生方式：作业控制命令 bg、fg、continue 等
默认动作：如果收到此信号的进程处于停止状态，则默认动作是使进程继续运行；否则默认动作是忽略信号
*** SIGEMT
产生方式：由实现定义的硬件故障
默认动作：终止+core
*** SIGFPE
产生方式：表示一个算数运算异常。如除以 0、浮点溢出等
默认动作：终止+core
*** SIGHUP
产生方式：
1. 如果终端接口检测到一个连接断开，则将此信号发送给与该终端相关的控制进程（会话首进程）。仅当终端的 CLOCAL 标志没有设置时，在前面所述条件下才会产生此信号。
2. 如果会话首进程终止也会产生此信号。这种情况，此信号会送给前台进程组中的每一个进程
默认动作：终止
常用技巧：通常捕捉此信号用来通知守护进程再次读取他们的配置文件。原因是，守护进程不会有控制终端，通常绝不会接收此种信号
*** SIGILL
产生方式：表示进程已执行一条非法硬件指令
默认动作：终止+core
*** SIGINT
产生方式：当用户按中断键(ctrl+c)时产生。终端驱动程序山城此信号并发送至前台进程组中的每一个进程
默认动作：终止
*** SIGIO
产生方式：一个异步 IO 事件会产生此信号
默认动作：linux 默认是终止，freebsd 和 macos 默认忽略
*** SIGIOT
产生方式：由实现定义的硬件故障
默认动作：终止+core
*** SIGKILL
产生方式：kill 命令
默认动作：终止
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
*** SIG
产生方式：
默认动作：
